AWSTemplateFormatVersion: '2010-09-09'

Description:
  The template used to create an ECS Cluster from the ECS Console.

Parameters:

  ECSClusterName:
    Type: String
    Description: Specifies the ECS Cluster Name with which the resources would be associated
    Default: everlasting-gecko-ub6ome

  # SecurityGroupIds:
  #   Type: CommaDelimitedList
  #   Description: Optional - Specifies the Comma separated list of the Security Group Id of an existing Security Group.
  #   Default: ''

  # VpcId:
  #   Type: String
  #   Description: Optional - Specifies the ID of an existing VPC in which to launch your container instances. If you specify a VPC ID, you must specify a list of existing subnets in that VPC. If you do not specify a VPC ID, a new VPC is created with at least 1 subnet.
  #   Default: ''
  #   AllowedPattern: '^(?:vpc-[0-9a-f]{8,17}|)$'
  #   ConstraintDescription: VPC Id must begin with 'vpc-' and have a valid uuid

  # SubnetIds:
  #   Type: CommaDelimitedList
  #   Description: Optional - Specifies the Comma separated list of existing VPC Subnet Ids where ECS instances will run
  #   Default: ''

Resources:

# https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-ecs-cluster.html
  CruddurECSCluster:
    Type: AWS::ECS::Cluster
    Properties:

      ClusterName: !Ref ECSClusterName

      CapacityProviders:
        - FARGATE
#        - FARGATE_SPOT

      ClusterSettings:
        - Name: containerInsights
          Value: disabled

      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT

      Tags:
        - Key: Environment
          Value: Production

#https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-ecs-service.html
  CruddurFrontend:
    Type: AWS::ECS::Service
    Properties:
      AvailabilityZoneRebalancing: ENABLED
#      CapacityProviderStrategy:
#        - CapacityProviderStrategyItem
      Cluster: !Ref CruddurECSCluster
#      DeploymentConfiguration:
#        DeploymentConfiguration
#      DeploymentController:
#        DeploymentController
      DesiredCount: 1
      EnableECSManagedTags: true
      EnableExecuteCommand: true
#      ForceNewDeployment:
#        ForceNewDeployment
#      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        # - AdvancedConfiguration:
        # - AdvancedConfiguration
        - ContainerName: frontend-react
          ContainerPort: 3000
#        - LoadBalancerName: String
          TargetGroupArn: !ImportValue CruddurFrontendTG
#      Monitoring:
#        MonitoringConfiguration
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !ImportValue CruddurEcsSg
          Subnets:
            - !ImportValue CruddurPrivateSubnet1
            - !ImportValue CruddurPrivateSubnet2
#      PlacementConstraints:
#        - PlacementConstraint
#      PlacementStrategies:
#        - PlacementStrategy
#      PlatformVersion: String
      PropagateTags: SERVICE
#      Role: String
#      SchedulingStrategy: String
      ServiceConnectConfiguration:
 #       AccessLogConfiguration:
 #         ServiceConnectAccessLogConfiguration
        Enabled: true
        # LogConfiguration:
        #   LogConfiguration
        Namespace: cruddur
        Services:
          - ClientAliases:
#             DnsName: String
              - Port: 3000
#           TestTrafficRules:
#             ServiceConnectTestTrafficRules
            DiscoveryName: frontend-react
#             IngressPortOverride: Integer
            PortName: frontend-react
#           Timeout:
#           TimeoutConfiguration
#           Tls:
#              ServiceConnectTlsConfiguration
      ServiceName: frontend-react
      # ServiceRegistries:
      #   - ServiceRegistry
      Tags:
        - Key: Environment
          Value: Production
      TaskDefinition: frontend-react
#      VolumeConfigurations:
#        - ServiceVolumeConfiguration
#      VpcLatticeConfigurations:
#        - VpcLatticeConfiguration


  CruddurBackend:
    Type: AWS::ECS::Service
    Properties:
      AvailabilityZoneRebalancing: ENABLED
#      CapacityProviderStrategy:
#        - CapacityProviderStrategyItem
      Cluster: !Ref CruddurECSCluster
#      DeploymentConfiguration:
#        DeploymentConfiguration
#      DeploymentController:
#        DeploymentController
      DesiredCount: 1
      EnableECSManagedTags: true
      EnableExecuteCommand: true
#      ForceNewDeployment:
#        ForceNewDeployment
#      HealthCheckGracePeriodSeconds: "60"
      LaunchType: FARGATE
      LoadBalancers:
        # - AdvancedConfiguration:
        # - AdvancedConfiguration
        - ContainerName: backend-flask
          ContainerPort: 4567
#        - LoadBalancerName: String
          TargetGroupArn: !ImportValue CruddurBackendTG
#      Monitoring:
#        MonitoringConfiguration
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !ImportValue CruddurEcsSg
          Subnets:
            - !ImportValue CruddurPrivateSubnet1
            - !ImportValue CruddurPrivateSubnet2

#      PlacementConstraints:
#        - PlacementConstraint
#      PlacementStrategies:
#        - PlacementStrategy
      PropagateTags: SERVICE
#      Role: String
#      SchedulingStrategy: String
      ServiceConnectConfiguration:
 #       AccessLogConfiguration:
 #         ServiceConnectAccessLogConfiguration
        Enabled: true
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: /ecs/cruddur-backend
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: ecs 
        # LogConfiguration:
        #   LogConfiguration
        Namespace: cruddur
        Services:
          - ClientAliases:
#             DnsName: String
              - Port: 4567
#             TestTrafficRules:
#                ServiceConnectTestTrafficRules
            DiscoveryName: backend-flask
#             IngressPortOverride: Integer
            PortName: backend-flask
#           Timeout:
#           TimeoutConfiguration
#           Tls:
#             ServiceConnectTlsConfiguration
      ServiceName: backend-flask
      # ServiceRegistries:
      #   - ServiceRegistry
      Tags:
        - Key: Environment
          Value: Production
      TaskDefinition: backend-flask
#      VolumeConfigurations:
#        - ServiceVolumeConfiguration
#      VpcLatticeConfigurations:
#        - VpcLatticeConfiguration

  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue CruddurVPC
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds:
        - !ImportValue CruddurPrivateSubnet1
        - !ImportValue CruddurPrivateSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSg
      PrivateDnsEnabled: true

  ECRApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue CruddurVPC
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      SubnetIds:
        - !ImportValue CruddurPrivateSubnet1
        - !ImportValue CruddurPrivateSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSg
      PrivateDnsEnabled: true
  ECRDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue CruddurVPC
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      SubnetIds:
        - !ImportValue CruddurPrivateSubnet1
        - !ImportValue CruddurPrivateSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSg
      PrivateDnsEnabled: true

  VPCEndpointSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTPS from ECS tasks to VPC endpoints
      VpcId: !ImportValue CruddurVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !ImportValue CruddurEcsSg
  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue CruddurVPC
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      SubnetIds:
        - !ImportValue CruddurPrivateSubnet1
        - !ImportValue CruddurPrivateSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSg
      PrivateDnsEnabled: true

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/cruddur-backend
      RetentionInDays: 7


# Outputs:

#   ECSCluster:
#     Description: The created cluster.
#     Value: !Ref ECSCluster