#!/bin/bash
set -a
source .env
set +a


ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
aws ecr get-login-password --region "$AWS_REGION" | \
docker login \
    --username AWS \
    --password-stdin \
    "$ECR_REGISTRY"
